Feature/favorites page
AltysS/travelAroundUkraine pull request #115
Opened 2022-12-06 10:16 UTC by AltysS

2022-12-06 22:17 UTC, Ahmed-Fahmy-Dev requested changes

2022-12-06 22:17 UTC, Ahmed-Fahmy-Dev commented on client/src/AppRoutes.js
> +import FavoritesPage from './pages/Favorites/Favorites';
why import favorites page individually and break the schema of page imports we all created?
please check how all pages are imported through index file and follow the pattern

2022-12-06 22:17 UTC, Ahmed-Fahmy-Dev commented on client/src/store/index.js
> +import inFavoritesSlice from './slices/inFavorites/inFavorites';
please follow the naming schema
```suggestion
import inFavoritesReducer from './slices/inFavorites/inFavorites';
```

2022-12-06 22:17 UTC, Ahmed-Fahmy-Dev commented on client/src/store/slices/inFavorites/inFavorites.js
> +      });
you dont need that.  just import axiosconfig and use it.

we already have an axios interceptor configured and the token is added automatically if it exists

2022-12-06 22:17 UTC, Ahmed-Fahmy-Dev commented on client/src/store/slices/inFavorites/inFavorites.js
> +
no need for all this . just delete.  it is stated clearly in the documentation that wish list is only available for authorized users:

![image](https://user-images.githubusercontent.com/107735322/206032923-f1b24b7a-0cb2-46fd-9a92-bceefddc8786.png)

2022-12-06 22:17 UTC, Ahmed-Fahmy-Dev commented on client/src/store/slices/inFavorites/inFavorites.js
> +    }
not needed

2022-12-06 22:17 UTC, Ahmed-Fahmy-Dev commented on client/src/store/slices/inFavorites/inFavorites.js
> +      .split(',')
not needed. )))

just keep it simple please

2022-12-06 22:17 UTC, Ahmed-Fahmy-Dev commented on client/src/pages/Favorites/Favorites.js
> +import React, { useEffect } from 'react';
please keep our file structure organized and follow one schema.  naming items randomly looks very unprofessional.


![image](https://user-images.githubusercontent.com/107735322/206033456-9f256e65-018a-409f-aea3-e238f15fe435.png)

2022-12-06 22:17 UTC, Ahmed-Fahmy-Dev commented on client/src/pages/Favorites/Favorites.js
> +                id={_id}
```suggestion
                id={_id} itemNo={itemNo}
```

please add itemNo  cause it is needed for the useNavigate hook i created

2022-12-06 22:17 UTC, Ahmed-Fahmy-Dev commented on client/src/pages/Favorites/Favorites.js
> +      {inFavorites.length === 0 && (
just use direct conditional rendering.  

inFavorites.length === 0 ?  REDNER "no items found" :   PRODUCTS

2022-12-06 22:17 UTC, Ahmed-Fahmy-Dev commented on client/src/store/slices/inFavorites/inFavorites.js
> +    },
so complicated.  will call u tomorrow and discuss with u how it could be simpler.

please remember, the simpler the code which gets the job done, the more pro u r...

2022-12-08 08:41 UTC, AltysS commented on client/src/AppRoutes.js
> +import FavoritesPage from './pages/Favorites/Favorites';
solved

2022-12-08 08:43 UTC, AltysS commented on client/src/store/index.js
> +import inFavoritesSlice from './slices/inFavorites/inFavorites';
solved

2022-12-08 08:49 UTC, AltysS commented on client/src/store/slices/inFavorites/inFavorites.js
> +      });
solved at all cases

2022-12-08 08:52 UTC, AltysS commented on client/src/store/slices/inFavorites/inFavorites.js
> +
Need to be discussed before fixing it as I guess it`s a good idea to provide customers with adding items to the wishlist even if they are not logged in. Also, it`s server documentation that provides information about how we can work with it, and still not a guideline or requirement regarding how our final project should be. Please, contact me to discuss this question

2022-12-08 08:53 UTC, AltysS commented on client/src/store/slices/inFavorites/inFavorites.js
> +    }
has to be disscussed

2022-12-08 08:53 UTC, AltysS commented on client/src/store/slices/inFavorites/inFavorites.js
> +      .split(',')
same here. But agree that a code looks quite complicated here

2022-12-08 08:54 UTC, AltysS commented on client/src/pages/Favorites/Favorites.js
> +import React, { useEffect } from 'react';
solved

2022-12-08 09:13 UTC, AltysS commented on client/src/pages/Favorites/Favorites.js
> +                id={_id}
included, solved

2022-12-08 09:29 UTC, AltysS commented on client/src/pages/Favorites/Favorites.js
> +      {inFavorites.length === 0 && (
solved

2022-12-08 10:47 UTC, AltysS commented on client/src/store/slices/inFavorites/inFavorites.js
> +    },
this comment is not solved/ Please, contact me to disscuss

2022-12-09 12:53 UTC, HIMDanny commented on client/src/pages/FavoritesPage/FavoritesPage.js
> +                  inFavorites={checkForFavorites ? !!checkForFavorites : false}
`checkForFavorites` returns you object or undefined which is true or false. In that case, no neediness for ternary expression here
```suggestion
                  inFavorites={!!checkForFavorites}
```

2022-12-12 13:02 UTC, Ahmed-Fahmy-Dev commented on client/src/store/slices/inFavorites/inFavorites.js
> +
already discussed.  logic will be changed to be simpler

2022-12-12 13:04 UTC, Ahmed-Fahmy-Dev commented on client/src/store/slices/inFavorites/inFavorites.js
> +    },
already discussed.  code will be edited in refactoring stage

2022-12-12 13:07 UTC, Ahmed-Fahmy-Dev approved these changes
to be refactored as discussed with owner

2022-12-12 14:47 UTC, HIMDanny approved these changes

2022-12-12 14:47 UTC, merged