Hot Deals Section Tests
AltysS/travelAroundUkraine pull request #60
Opened 2022-11-08 13:13 UTC by Vladislav2498

2022-11-08 13:30 UTC, Ahmed-Fahmy-Dev reviewed
please check Eslint errors:

![image](https://user-images.githubusercontent.com/107735322/200577399-bbb10429-1f28-4ede-b8fd-e5a97d47a6d0.png)

2022-11-08 13:30 UTC, Ahmed-Fahmy-Dev commented on client/src/pages/HomePage/HomePage.js
> +            {/*<CardContainer />*/}
this is not corrent.. please leave it as it is as i already wrote the homepage test and mocked this component.

2022-11-08 13:30 UTC, Ahmed-Fahmy-Dev commented on client/src/components/CardContainer/CardContainer.test.js
>  });
please mock the MUI components of typography
you can try to mock Swiper too

2022-11-10 10:48 UTC, Ahmed-Fahmy-Dev requested changes
not approved.    
CardItem.test.js  is not complete.   MUI components have to be mocked there too

2022-11-10 10:49 UTC, Ahmed-Fahmy-Dev commented
ESlint errors fixed by myself.

2022-11-10 14:14 UTC, Ahmed-Fahmy-Dev approved these changes

2022-11-10 14:15 UTC, Ahmed-Fahmy-Dev approved these changes
approved. 

i added a hot fix by myself.. please check commit message for details

2022-11-10 14:17 UTC, AltysS approved these changes

2022-11-10 14:17 UTC, merged