Feature/catalogue features
AltysS/travelAroundUkraine pull request #93
Opened 2022-11-25 08:15 UTC by AltysS

2022-11-27 15:55 UTC, AlinaPalyvoda approved these changes
I have no comments. I agree with everything. Great job!

2022-11-28 16:16 UTC, Ahmed-Fahmy-Dev requested changes
as a final comment, the file structure in the store is wrong.  i guess you took Roman's code as an example.   you have to create a folder for each slice, where the slice itself will be located plus the test file.  

so the structure is as follows:       store/catalogueSlice/catalogueSlice.js

2022-11-28 16:16 UTC, Ahmed-Fahmy-Dev commented on client/src/store/index.js
> +  reducer: { userReducer, catalogueReducer },
```suggestion
  reducer: { userReducer, 
  catalogue: catalogueReducer },
```

2022-11-28 16:16 UTC, Ahmed-Fahmy-Dev commented on client/src/api/getProducts.js
> +    const { data } = await axiosConfig.get('/products');
```suggestion
    const { data } = await axios('/products');
```

simpler

2022-11-28 16:16 UTC, Ahmed-Fahmy-Dev commented on client/src/pages/CataloguePage/CataloguePage.js
> +  const products = useSelector((state) => state.catalogueReducer.products, shallowEqual);
```suggestion
  const products = useSelector((store) => store.catalogue.products, shallowEqual);
```

2022-11-28 16:16 UTC, Ahmed-Fahmy-Dev commented on client/src/pages/CataloguePage/CataloguePage.js
> +  }, []);
this is not correct,   we are using Redux toolkit.  the async request has to be encapuslated in the Slice file.  and just called in here.    you can check my tourSlice as an example. you will find a THUNK function called fetchTour

isLoading logic also has to be encapsulated into the Redux thunk function.

2022-11-29 06:53 UTC, AltysS commented on client/src/store/index.js
> +  reducer: { userReducer, catalogueReducer },
solved

2022-11-29 07:24 UTC, AltysS commented on client/src/store/index.js
> +  reducer: { userReducer, catalogueReducer },
sovled

2022-11-29 07:24 UTC, AltysS commented on client/src/api/getProducts.js
> +    const { data } = await axiosConfig.get('/products');
solved

2022-11-29 07:25 UTC, AltysS commented on client/src/pages/CataloguePage/CataloguePage.js
> +  const products = useSelector((state) => state.catalogueReducer.products, shallowEqual);
solved

2022-11-29 11:45 UTC, Ahmed-Fahmy-Dev approved these changes
approved for setIsLoading to be fixed by encapsulating itto getProducts function

2022-11-29 11:46 UTC, merged